@URL = http://127.0.0.1:5000
###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "juan",
    "apellido": "pereyra",
    "provincia": "buenos aires",
    

}

###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario/1

#############################################

###
GET {{URL}}/dietas


####################################################
# Plan Semanal
####################################################

### Obtener todos los planes semanales
GET {{URL}}/plan_semanal

###

### Crear plan semanal
POST {{URL}}/plan_semanal
Content-Type: application/json

{
    "fecha": "2026-07-06",
    "nombre": "Plan Semana 1",
    "id_usuario": 1
}

###

### Actualizar plan semanal con id=1
PUT {{URL}}/plan_semanal/1
Content-Type: application/json

{
    "fecha": "2026-07-13",
    "nombre": "Plan Semana Actualizado",
    "id_usuario": 1
}
####################################################
# Ingredientes
####################################################

### Obtener todos los ingredientes
GET {{URL}}/ingredientes
###

### Eliminar plan semanal con id=1
DELETE {{URL}}/plan_semanal/1




